deploy: add check update steps

diff --git a/.github/workflows/dst-server.yml b/.github/workflows/dst-server.yml
--- a/.github/workflows/dst-server.yml
+++ b/.github/workflows/dst-server.yml
@@ -5,18 +5,60 @@ permissions:
 
 on:
   schedule:
-    - cron: '0 0 * * *' # run every midnight
+    - cron: '0 1 * * *' # run every hour
   workflow_dispatch: # allow to run manually
 
 env:
   DOCKER_REGISTRY: docker.io
 
 jobs:
+  check-updates:
+    runs-on: ubuntu-latest
+    outputs:
+      should_build: ${{ steps.check.outputs.should_build }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: 'stable'
+
+      - name: Check Game Updates
+        id: check
+        run: |
+          # fetch latest image version
+          CUR_VERSION=$(curl -s https://registry.hub.docker.com/v2/repositories/dstgo/dst-server-x64/tags/ | jq -r '.results[].name' | grep -v '^latest$' | sort -rn | head -n 1)
+          if [[ -z "$CUR_VERSION" ]]; then
+            echo "Error: Failed to get latest Docker image version"
+            exit 1
+          fi
+          
+          # fetch latest dst version
+          LATEST_VERSION=$(go run ./framework/dontstarve/release/cmd/dstv latest)
+          if [[ -z "$LATEST_VERSION" ]] || ! [[ "$LATEST_VERSION" =~ ^[0-9]+$ ]]; then
+            echo "Error: failed to fetch latest version: $LATEST_VERSION"
+            exit 1
+          fi
+          
+          echo "Current version: $CUR_VERSION"
+          echo "Latest version: $LATEST_VERSION"
+          
+          # check if a new version is available
+          if (( CUR_VERSION >= LATEST_VERSION )); then
+            echo "should_build=false" >> $GITHUB_OUTPUT
+          else
+            echo "should_build=true" >> $GITHUB_OUTPUT
+          fi
+
   dst-build-push:
+    needs: check-updates
+    if: needs.check-updates.outputs.should_build == 'true'
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        arch: [x64, x86]
+        arch: [ x64, x86 ]
     env:
       IMAGE_NAME: dstgo/dst-server-${{ matrix.arch }}
       DOCKERFILE_PATH: deploy/dontstarve/docker/${{ matrix.arch }}/Dockerfile
@@ -52,8 +94,6 @@ jobs:
         run: |
           docker tag ${{ env.IMAGE_NAME }}:${{ env.TEMP_TAG }} ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
           docker tag ${{ env.IMAGE_NAME }}:${{ env.TEMP_TAG }} ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.DST_VERSION }}
-          echo "Tagged images:"
-          docker images | grep ${{ env.IMAGE_NAME }}
 
       - name: Login to Docker Hub
         uses: docker/login-action@v2
@@ -65,6 +105,10 @@ jobs:
         run: |
           docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
           docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.DST_VERSION }}
-          echo "Pushed images:"
-          echo "${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
-          echo "${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.DST_VERSION }}"
+
+      - name: Clean up Docker images
+        if: always()
+        run: |
+          docker rmi ${{ env.IMAGE_NAME }}:${{ env.TEMP_TAG }}
+          docker rmi ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
+          docker rmi ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.DST_VERSION }}
