deploy: fix missing temp tag for local image (#20)
* deploy: fix missing temp tag for local image

* deploy: add x86 arch image

* deploy: refactor with matrix strategy

diff --git a/.github/workflows/dst-server.yml b/.github/workflows/dst-server.yml
--- a/.github/workflows/dst-server.yml
+++ b/.github/workflows/dst-server.yml
@@ -5,17 +5,22 @@ permissions:
 
 on:
   schedule:
-    - cron: '0 2 * * *' # run every-day at 2am
+    - cron: '0 0 * * *' # run every-day at midnight
   workflow_dispatch: # allow to run manually
 
 env:
   DOCKER_REGISTRY: docker.io
-  IMAGE_NAME: dstgo/dst-server
-  DOCKERFILE_PATH: deploy/dontstarve/docker/Dockerfile
 
 jobs:
-  build-and-push:
+  dst-build-push:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        arch: [x64, x86]
+    env:
+      IMAGE_NAME: dstgo/dst-server-${{ matrix.arch }}
+      DOCKERFILE_PATH: deploy/dontstarve/docker/${{ matrix.arch }}/Dockerfile
+      TEMP_TAG: temp-${{ matrix.arch }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -30,19 +35,23 @@ jobs:
           file: ${{ env.DOCKERFILE_PATH }}
           push: false
           load: true
-          tags: ${{ env.IMAGE_NAME }}:temp
+          tags: ${{ env.IMAGE_NAME }}:${{ env.TEMP_TAG }}
 
       - name: Get DST server version from image
         id: get_version
         run: |
-          VERSION=$(docker run --rm --entrypoint /bin/bash ${{env.IMAGE_NAME}} -c 'cat $DST_VERSION_FILE')
+          VERSION=$(docker run --rm ${{ env.IMAGE_NAME }}:${{ env.TEMP_TAG }})
+          if [[ -z "$VERSION" ]] || ! [[ "$VERSION" =~ ^[0-9]+$ ]]; then
+            echo "Error: Invalid or empty version number: $VERSION"
+            exit 1
+          fi
           echo "DST_VERSION=${VERSION}" >> $GITHUB_OUTPUT
           echo "DST_VERSION=${VERSION}"
 
       - name: Tag Docker image
         run: |
-          docker tag ${{ env.IMAGE_NAME }}:temp ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
-          docker tag ${{ env.IMAGE_NAME }}:temp ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.DST_VERSION }}
+          docker tag ${{ env.IMAGE_NAME }}:${{ env.TEMP_TAG }} ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
+          docker tag ${{ env.IMAGE_NAME }}:${{ env.TEMP_TAG }} ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.DST_VERSION }}
           echo "Tagged images:"
           docker images | grep ${{ env.IMAGE_NAME }}
 
